tags:
  subject:
    - human_presence
    - group_interaction
    - solitary_figure
    - domestic_animal
    - wild_animal
    - everyday_object
    - food_or_drink
    - living_thing
    - machine_or_device
    - symbolic_form
    - surreal_entity
    - abstract_shape

  action:
    - everyday_life
    - emotional_state
    - physical_motion
    - personal_care
    - human_connection
    - artistic_expression
    - intellectual_activity
    - stillness_or_waiting
    - ambiguous_gesture

  setting:
    - urban_environment
    - domestic_space
    - commercial_space
    - public_area
    - transportation_hub
    - natural_outdoor
    - abstract_space
    - imaginative_realm
    - nondescript_backdrop

  mood:
    - neutral
    - positive
    - negative
    - introspective
    - dramatic
    - surreal
    - ambiguous

  style:
    - naturalistic
    - stylized
    - flat_design
    - cinematic
    - retro_aesthetic
    - conceptual_art
    - visual_minimalism
    - expressive_illustration

  lighting:
    - ambient
    - soft
    - moody
    - warm
    - cold
    - directional
    - diffuse
    - mixed_sources

  camera_angle:
    - natural_perspective
    - elevated_view
    - downward_view
    - close_crop
    - over_the_shoulder
    - incidental_view
    - subjective_view
    
lm_studio:
  model: "gemma-3-4b-it"
  prompt_template: |
    Generate a stylized image prompt using the following tags: {tags}.

    Guidelines:
    - Combine the tags into a single, compact visual concept.
    - Output should be **comma-separated descriptive phrases** (no full sentences).
    - Use visually evocative language focused on **subject, setting, mood, style, and light**.
    - Avoid camera lingo, narrative phrasing, and redundancy.
    - Do NOT mention "photo", "image", or UI concepts.
    - Length: ideally 15–40 words max.

    Prompt:
    
comfy_ui:
  server_address: "127.0.0.1:8188" # Replace with your ComfyUI server address
  client_id: "" # Will be generated by the script
  output_directory: "output_images" # Directory to save generated images
  steps: 35
  width: 1536
  height: 1536

# MongoDB database configuration
mongodb:
  data_dir: "./mongodb_data"  # Directory to store MongoDB data files
  db_name: "stock_images"     # Database name
  collection: "images"        # Collection name for storing image metadata
  # connection_string: ""     # Optional: Custom MongoDB connection string (if using external MongoDB)