# config.yaml Example Structure
tags:
  subject:
    - anything
    - human_figure
    - group_of_people
    - child
    - elder
    - couple
    - animal
    - bird
    - aquatic_creature
    - fantasy_entity
    - mechanical_entity
    - shadow_silhouette
    - mythological_beast
    - alien_form
    - abstract_form
    - humanoid_robot

  action:
    - anything
    - emotional_expression
    - physical_activity
    - creative_process
    - conflict
    - rest
    - interaction
    - solitude
    - transformation
    - discovery
    - ritual

  setting:
    - anything
    - natural_landscape
    - urban_space
    - domestic_interior
    - industrial_area
    - mystical_realm
    - dreamlike_environment
    - outer_space
    - underwater_world
    - haunted_location
    - high_tech_lab
    - surreal_architecture
    - abandoned_place
    - minimal_environment
    - fantasy_realm

  mood:
    - anything
    - joyful
    - serene
    - melancholic
    - mysterious
    - ominous
    - chaotic
    - dreamy
    - introspective
    - euphoric
    - oppressive
    - uncanny
    - nightmarish
    - ambiguous

  style:
    - anything
    - realistic
    - cinematic
    - painterly
    - illustrative
    - graphic_novel
    - anime
    - abstract_art
    - glitchcore
    - surrealism
    - fantasy_art
    - low_poly
    - steampunk
    - vaporwave
    - brutalist
    - gothic

  lighting:
    - anything
    - natural_light
    - backlit
    - golden_hour
    - candlelit
    - overcast
    - neon_lit
    - moonlit
    - high_contrast
    - shadowy
    - cinematic_glow

  camera_angle:
    - anything
    - bird_eye
    - worm_eye
    - close_up
    - over_the_shoulder
    - wide_shot
    - surveillance_perspective
    - extreme_angle
    - fisheye
    
lm_studio:
  model: "gemma-3-4b-it"
  prompt_template: |
    Generate a concise, stylized image prompt based on these tags: {tags}.

    Guidelines:
    - Use **compact, comma-separated phrases**.
    - Focus on visual concepts: **subject**, **mood**, **setting**, **style**, and **lighting**.
    - Avoid full sentences, filler words, or redundant descriptions.
    - Do **not** include "a photo of", "an image of", or any camera jargon.
    - Limit to **40 words max**, ideally **1-3 punchy phrases**.
    - Avoid mentioning text, logos, UI, or anything non-visual.
    - Prompt should read like something for **Stable Diffusion** or **ComfyUI Flux** — fast, descriptive, visual.

    Prompt:

comfy_ui:
  server_address: "127.0.0.1:8188" # Replace with your ComfyUI server address
  client_id: "" # Will be generated by the script
  output_directory: "output_images" # Directory to save generated images
  steps: 35
  width: 1536
  height: 1536

# MongoDB database configuration
mongodb:
  data_dir: "./mongodb_data"  # Directory to store MongoDB data files
  db_name: "stock_images"     # Database name
  collection: "images"        # Collection name for storing image metadata
  # connection_string: ""     # Optional: Custom MongoDB connection string (if using external MongoDB)