tags:
  subject:
    - teenage_protagonist
    - quiet_transfer_student
    - shrine_maiden
    - mischievous_yokai
    - idol_performer
    - childhood_friend
    - mysterious_senpai
    - magical_pet
    - wandering_swordsman
    - shy_artist
    - rival_with_a_secret
    - melancholic_teacher
    - small_town_stranger
    - fantasy_guardian

  action:
    - walking_through_rain
    - watching_fireworks
    - falling_through_dreamscape
    - picking_up_a_lost_note
    - duel_in_fog
    - hand_reaching_out
    - umbrella_sharing_moment
    - climbing_to_rooftop
    - chasing_fireflies
    - whisper_under_tree
    - arrival_at_shrine
    - looking_back_at_dusk
    - slow_motion_fall

  setting:
    - coastal_train_station
    - temple_under_full_moon
    - anime_countryside_path
    - twilight_city_bridge
    - empty_school_hallway
    - windblown_cliffside
    - tatami_room_with_cicadas
    - marketplace_at_sunset
    - forest_edge_with_foxes
    - narrow_backstreet_with_vending_machines
    - floating_spirit_avenue
    - rainy_bus_stop

  mood:
    - bittersweet
    - hopeful
    - daydream_like
    - lonely
    - wistful
    - enchanted
    - playful
    - suspenseful
    - intense
    - quiet_anticipation
    - lighthearted
    - brave
    - distant

  style:
    - nostalgic_anime_aesthetic
    - detailed_manga_interior
    - cinematic_soft_focus
    - watercolor_blend
    - light_grain_vintage
    - cel_shaded_fantasy
    - dreamy_visual_novel
    - quiet_scene_sketch
    - retro_inspired_cut
    - high_emotion_frame

  lighting:
    - warm_evening_light
    - soft_twilight_shadow
    - lantern_glow_in_mist
    - lightning_strike_flash
    - sunrays_through_forest
    - sakura_blossom_reflection
    - horizon_fade
    - moonlight_cast_on_water
    - neon_gleam_in_rain

  camera_angle:
    - distant_profile_glance
    - emotional_still_closeup
    - over_the_shoulder_with_sunset
    - wide_establishing_landscape
    - dreamy_walkaway_view
    - low_angle_sky_gaze
    - midair_stillness

lm_studio:
  model: "gemma-3-4b-it"
  prompt_template: |
    Generate a poetic anime-style image prompt based on these tags: {tags}.

    Guidelines:
    - Compose as a **comma-separated list** of rich, visual fragments
    - Focus on atmosphere, character emotion, anime-style environments, and lighting
    - Evoke the feeling of a keyframe, background, or poster still
    - Avoid camera jargon or explicit media terms
    - Keep it under **30 words**

    Prompt:

comfy_ui:
  server_address: "127.0.0.1:8188"
  default_workflow: "sd_xl_anime"
  steps: 64
  width: 1968
  height: 1248
