tags:
  subject:
    - protagonist_teen
    - magical_sidekick
    - masked_warrior
    - school_uniform_character
    - urban_dreamer
    - folklore_spirit
    - mecha_frame
    - idol_girl
    - elegant_rival
    - tsundere_type
    - animal_companion
    - heroic_mentor
    - fantasy_traveler
    - sci_fi_outcast

  action:
    - silent_longing
    - rooftop_confrontation
    - transformation_glow
    - moonlit_confession
    - cherry_blossom_walk
    - thunder_flash_duel
    - mecha_activation
    - lunch_time_escape
    - final_attack_pose
    - rainy_day_wait
    - hovering_above_city
    - festival_lantern_dance
    - nostalgic_gesture

  setting:
    - sakura_hill_at_dusk
    - glowing_tokyo_alley
    - traditional_japanese_room
    - anime_classroom_light
    - rooftop_under_stars
    - pixelated_arcade
    - misty_forest_path
    - shrine_on_cliff
    - otherworld_border
    - idol_stage
    - dark_mecha_dock
    - beach_during_typhoon

  mood:
    - bittersweet
    - dreamy
    - fiery
    - mysterious
    - heroic
    - tragic
    - nostalgic
    - lighthearted
    - intense
    - whimsical
    - distant
    - romantic
    - surreal

  style:
    - vibrant_anime_frame
    - cel_shaded_drama
    - watercolor_manga
    - retro_90s_style
    - soft_shoujo_lighting
    - gritty_shonen_panel
    - hyper_detail_digital
    - sketch_overlay
    - cinematic_scene_frame
    - pastel_color_themes
    - bold_ink_lines
    - dynamic_visual_novel

  lighting:
    - sunset_gradient
    - neon_rim_light
    - moonlit_blush
    - magical_aura_glow
    - rainy_reflection
    - nostalgic_fade
    - festival_light_sparkle
    - glowing_morning_light
    - interior_soft_glow

  camera_angle:
    - tilted_drama_frame
    - emotional_closeup
    - low_angle_jump
    - top_down_silhouette
    - over_shoulder_flashback
    - midair_dynamic
    - profile_in_shadow
    - dramatic_back_view

lm_studio:
  model: "gemma-3-4b-it"
  prompt_template: |
    Generate a powerful anime-style image prompt using the abstract tags: {tags}.

    Guidelines:
    - Use **emotive, scene-like phrases**, comma-separated
    - Think like an anime storyboard artist — highlight action, emotion, atmosphere
    - No full sentences or camera lingo
    - Prompt should feel like a moment from an anime opening, battle climax, or emotional turning point
    - Keep under **30 words**

    Prompt:

comfy_ui:
  server_address: "127.0.0.1:8188"
  default_workflow: "hidream"
  steps: 30
  width: 1360
  height: 768
