tags:
  subject:
    - symbolic_figure
    - contemplative_portrait
    - broken_statue
    - everyday_body
    - gestural_silhouette
    - sleeping_form
    - veiled_woman
    - abstract_face
    - floating_drapery
    - anatomical_study
    - blooming_organism
    - organic_architecture
    - rusted_tool
    - nostalgic_object
    - decaying_structure
    - domestic_still_life
    - spiritual_totem
    - surreal_animal
    - dreamlike_child
    - ritual_pose

  action:
    - stillness
    - gentle_motion
    - introspection
    - slow_embrace
    - reaching_out
    - falling_apart
    - ritual_dance
    - solitary_waiting
    - transformation
    - rising_or_floating
    - shadow_play
    - subtle_disintegration

  setting:
    - sterile_gallery_space
    - abandoned_apartment
    - crumbling_concrete_room
    - dreamlike_courtyard
    - soft_draped_stage
    - flooded_attic
    - modernist_studio
    - foggy_garden
    - surreal_library
    - crumbled_shrine
    - forest_within_walls
    - psychological_interior
    - ambiguous_architecture

  mood:
    - contemplative
    - melancholic
    - serene
    - absurd
    - sacred
    - nostalgic
    - poetic
    - heavy_with_memory
    - lonely
    - vulnerable
    - elegant
    - surreal
    - abstracted

  style:
    - surrealism
    - expressionism
    - classical_sketch
    - poetic_realism
    - abstract_expressionism
    - bauhaus_minimalism
    - postmodern_assemblage
    - naive_art
    - mixed_media_painting
    - soft_pastel_study
    - figurative_exploration
    - brutal_collage
    - sculpture_mockup
    - contemporary_drawing

  lighting:
    - moody_gradient
    - spotlight_fade
    - dusty_window_light
    - ambient_gloom
    - natural_diffusion
    - warm_interior_haze
    - fading_twilight
    - fragmented_shadows
    - candle_flicker
    - minimal_sun_glow

  camera_angle:
    - frontal_view
    - slightly_off_center
    - softened_close_up
    - elevated_gaze
    - isolated_wide_shot
    - behind_thin_veil
    - top_down_isolation
    - distant_long_shot

lm_studio:
  model: "gemma-3-4b-it"
  prompt_template: |
    You are a visual poet generating prompts for evocative contemporary or surreal fine art.

    Using these tags: {tags}, generate a gentle, emotionally resonant visual prompt for an AI art model.

    Guidelines:
    - Use **comma-separated artistic fragments**, no full sentences
    - Let the visual tone guide the style — poetic, expressive, symbolic
    - Avoid technical or camera terminology
    - Think like a painter or installation artist, blending form, mood, material
    - Keep under **25 words**

    Prompt:

comfy_ui:
  server_address: "127.0.0.1:8188"
  default_workflow: "sd_xl"
  steps: 64
  width: 1024
  height: 1024
