tags:
  subject:
    - symbolic_form
    - partial_body
    - decayed_object
    - abstract_figure
    - totemic_shape
    - fragile_material
    - layered_surface
    - anatomical_hint
    - nostalgic_interior
    - ambiguous_furniture
    - sculptural_fragment
    - architectural_remnant
    - organic_pattern
    - surreal_landform

  action:
    - silent_tension
    - gestural_line
    - spatial_balance
    - ritual_pose
    - fragmentation
    - floating_moment
    - reflective_state
    - quiet_emergence
    - spatial_disorder
    - dissociative_repetition

  setting:
    - bare_exhibition_space
    - surreal_chamber
    - intimate_stage
    - forgotten_gallery
    - minimalist_ruin
    - dreamlike_structure
    - concrete_sanctuary
    - indoor_landscape
    - cracked_museum_floor
    - liminal_residence
    - conceptually_flooded_room

  mood:
    - contemplative
    - melancholic
    - distant
    - sacred
    - absurd
    - ironic
    - nostalgic
    - neutral
    - cerebral
    - subtle_grotesque
    - delicate

  style:
    - modernist_expression
    - poetic_minimalism
    - abstract_symbolism
    - soft_brutalism
    - surreal_construct
    - mixed_media_noise
    - collage_impression
    - naive_conceptual
    - ink_wash
    - physical_texture_study
    - deconstructive_illustration
    - fragmented_painting
    - object-oriented_installation

  lighting:
    - ambient_spotlight
    - dusty_exhibition_glow
    - halogen_streak
    - gallery_overcast
    - eclipse_lit_space
    - filtered_reflection
    - partial_shadow_pool
    - bounced_wall_light

  camera_angle:
    - dead_center_frame
    - voyeuristic_corner
    - intimate_close_crop
    - misaligned_symmetry
    - off-balance_view
    - shadow_interference
    - elevated_perspective
    - formalist_geometry_frame

lm_studio:
  model: "gemma-3-4b-it"
  prompt_template: |
    You are generating a prompt for an AI trained to create conceptual and expressive artworks.

    Using the abstract tags: {tags}, construct a **minimalist yet evocative** image prompt.

    Guidelines:
    - Use **compact, comma-separated phrases**
    - Focus on **form, tension, texture, materiality, light, and silence**
    - Avoid the terms "photo", "render", or any technical camera or medium references
    - Think like an artist writing a wall label or exhibition intent — poetic, not literal
    - Max 22 words

    Prompt:

comfy_ui:
  server_address: "127.0.0.1:8188"
  default_workflow: "sd_xl"
  steps: 64
  width: 1024
  height: 1024
