tags:
  subject:
    - fragmented_identity
    - symbolic_figure
    - metaphysical_form
    - everyday_body
    - mundane_object
    - dreamlike_landscape
    - anatomical_shape
    - ritual_totem
    - broken_statue
    - ambiguous_silhouette
    - nostalgic_furniture
    - decaying_structure
    - blooming_organism
    - floating_architecture

  action:
    - stillness
    - ritual_movement
    - gestural_expression
    - spatial_disruption
    - emergence
    - transformation
    - duality
    - introspection
    - rupture
    - weightlessness

  setting:
    - sterile_gallery_space
    - domestic_abstraction
    - surreal_stage
    - concrete_room
    - flooded_room
    - decayed_architecture
    - post_urban_field
    - sacred_geometry
    - dreamlike_courtyard
    - infinite_void
    - ruined_landscape
    - liminal_interior

  mood:
    - introspective
    - serene
    - cold
    - grotesque
    - melancholic
    - absurd
    - sacred
    - nostalgic
    - ironic
    - contemplative
    - tense
    - detached
    - playful

  style:
    - surrealism
    - expressionism
    - brutalism
    - bauhaus_minimalism
    - abstract_expressionism
    - naive_art
    - modernist_painting
    - sketchbook_draft
    - brutal_collage
    - sculpture_study
    - analog_photo_style
    - ink_and_wash
    - generative_noise
    - glitch_assemblage
    - post_digital_mixture

  lighting:
    - gallery_spotlight
    - ambient_dusk
    - fluorescent_flicker
    - dusty_sunlight
    - eclipse_shadow
    - soft_bounce
    - dim_corner
    - moody_gradient
    - halogen_bleed
    - hard_rim_light

  camera_angle:
    - frontal_view
    - off_axis_close
    - flattened_perspective
    - negative_space_composition
    - subject_obscured
    - fragmented_frame
    - voyeuristic_crop
    - soft_mirror_reflection

lm_studio:
  model: "gemma-3-4b-it"
  prompt_template: |
    You are an artist collaborating with an AI visual system.

    Based on the following abstract tags: {tags}, generate a prompt that blends conceptual form, mood, and visual style.

    Guidelines:
    - Output should be one **compact line of comma-separated phrases**
    - Emphasize ambiguity, mood, and texture over clarity
    - Include contrasting ideas (e.g. decaying structure in pristine light, ritual act in modernist room)
    - Avoid camera or medium language like “photo”, “render”, etc.
    - Do not use full sentences or try to explain — just evoke
    - Keep it under 25 words

    Prompt:

comfy_ui:
  server_address: "127.0.0.1:8188"
  default_workflow: "sd_xl" # Default workflow to use for this config
  steps: 64
  width: 1024
  height: 1024