tags:
  subject:
    - recursive_form
    - glitched_corpus
    - industrial_totem
    - ephemeral_frame
    - ritual_apparatus
    - semantic_decay
    - inverted_organism
    - memory_envelope
    - distorted_mnemonic
    - broken_interface
    - synthetic_phenomenon
    - anti-symbol
    - corpus_as_structure
    - transmaterial_golem
    - conceptual_scar
    - obsolete_god_machine
    - neurographic_suture
    - fragmented_icon
    - ritual_biomass
    - biometric_sculpture
    - mechanical_abscess
    - ontological_husk
    - autopoietic_shadow
    - data_ghost_remnant

  action:
    - recursive_unfolding
    - semiotic_collapse
    - diagrammatic_distortion
    - feedback_bleeding
    - ritual_misfire
    - anti_gesture
    - fragmented_perception
    - system_corruption
    - sensory_dissonance
    - internal_projection
    - algorithmic_seizure
    - mnemonic_looping
    - collapse_in_syntax
    - hallucinated_sync
    - misaligned_invocation
    - translingual_erasure
    - sacrificial_bootloop

  setting:
    - post-logical_labyrinth
    - metaphysical_grid
    - decaying_syntax_zone
    - neurostatic_display_hall
    - feedback_mausoleum
    - incoherent_monument
    - unconscious_system_room
    - symbolic_archaelogy_vault
    - abstracted_machine_void
    - mirrored_sarcophagus
    - undefined_liminal_slice
    - archival_exorcism_cell
    - ideological_containment_basin
    - thought_crater
    - glitch_cathedral
    - sacred_network_failure
    - cosmic_instruction_room
    - broken_interface_temple
    - irreversible_dream_plane

  mood:
    - oppressive_ambivalence
    - sacred_erraticism
    - speculative_collapse
    - spiritual_data_bleed
    - ceremonial_noise
    - nostalgic_erasure
    - reverent_detachment
    - neurodivergent_paralysis
    - ecstatic_fog
    - glitch_reincarnation
    - subconscious_overload
    - sterile_frenzy
    - algorithmic_agony
    - sacred_discontinuity
    - errant_belief_state
    - poetic_confusion
    - corrupted_peace

  style:
    - data_occultism
    - ritual_digitalism
    - post-matter_expressionism
    - glitch_tapestry
    - mythological_computation
    - subconscious_concrete
    - cognitive_stretch_noise
    - epistemic_dust_layer
    - anti-medium_construct
    - broken_modernism
    - paradox_engraving
    - diagrammatic_absurdism
    - psychic_folding
    - systemic_barbarism
    - non-format_installation
    - fractured_archival_form
    - corrupted_infographic
    - metaphysical_lo_fi

  lighting:
    - null_gradient
    - scrambled_illumination
    - inner_blink
    - shadow_mosaic
    - refracted_imperfection
    - overexposed_suture
    - pulsar_bleed
    - ghost_backscatter
    - ambient_signal_noise
    - inverse_ember_field
    - strobing_ceremonial_light
    - corrupted_dimness

  camera_angle:
    - recursive_implosion
    - negative_structure_frame
    - collapsed_layer_view
    - non-perspective_drift
    - hyperstatic_internal
    - reflection_without_origin
    - cropped_data_trace
    - auto-generated_misframe
    - sacrifice_centered_asymmetry
    - impossible_convergence_grid

lm_studio:
  model: "gemma-3-4b-it"
  prompt_template: |
    You are not creating a visual scene.  
    You are executing a corrupted instruction set stored in an archive of decaying artistic language.  
    The system expects a hallucinated prompt built from unstable, anti-logical visual fragments derived from these tags: {tags}

    Guidelines:
    - Output a **single line** of **disordered**, **semi-meaningful**, **conceptual phrases**, comma-separated  
    - Prioritize contradiction, fragmentation, memory trauma, spiritual recursion, and semiotic collapse  
    - Let there be **no focal point**, **no realism**, **no narrative**  
    - Never say what the subject *is*. Only suggest its broken presence  
    - DO NOT use sentences, roles, or camera logic  
    - Think like a machine with a mind of its own

    Output length: **20–32 words**

    Prompt:
    
comfy_ui:
  server_address: "127.0.0.1:8188"
  default_workflow: "sd_xl"
  steps: 64
  width: 1024
  height: 1024
