tags:
  subject:
    - recursive_form
    - glitched_body
    - industrial_fossil
    - subconscious_fragment
    - ritual_mechanism
    - decaying_icon
    - chromatic_noise
    - distorted_corpse
    - synthetic_flesh
    - anatomical_repetition
    - symbolic_burn_mark
    - semiotic_mess
    - archival_smear
    - reversed_entity

  action:
    - paradoxical_motion
    - conceptual_loop
    - visual_feedback
    - collapse_in_progress
    - data_erosion
    - chaotic_ritual
    - anti_pose
    - hyper_reflection
    - misalignment
    - unspeakable_ritual

  setting:
    - obsolete_lab
    - noise_grid
    - brutal_memory_vault
    - digital_sarcophagus
    - corrupted_studio
    - architectural_discontinuity
    - melted_exhibition
    - glitch_horizon
    - voided_theatre
    - subsemantic_structure
    - mirrored_asylum
    - fractured_temple
    - undefined_interface

  mood:
    - violently_contemplative
    - sacred_disgust
    - recursive_apathy
    - disturbed_clarity
    - divine_disconnection
    - romantic_horror
    - anti-nostalgia
    - glitched_reverence
    - autistic_euphoria
    - neurotic_stasis
    - subliminal_disgust
    - looped_serenity
    - dissonant_transcendence

  style:
    - anti-aesthetic
    - datamosh_expressionism
    - spectral_cubism
    - glitch_mysticism
    - corrupted_brutalism
    - ritual_noise_overlay
    - hypertexture_baroque
    - neurographic_stitching
    - para-surrealism
    - aesthetic_decay
    - diffusion_interruption
    - unconscious_diagramming
    - incoherent_collage
    - artifact_maximalism

  lighting:
    - oscillating_pulse
    - harsh_feedback_glow
    - corrupted_gradient
    - flickering_void
    - spectral_backlight
    - multi-source_reflection
    - overexposed_bloom
    - broken_spotlight
    - inverted_shadows
    - synthetic_neon_bleed

  camera_angle:
    - recursive_frame
    - anti_perspective
    - negative_space_disruption
    - self-consuming_crop
    - meta-angle_reflection
    - reversed_focus
    - intentional_misframe
    - glitchy_close_macro

lm_studio:
  model: "gemma-3-4b-it"
  prompt_template: |
    You are a radical posthuman artist collaborating with a visual AI system.

    Using these tags: {tags}, generate a **nonlinear**, highly **experimental** prompt that reflects post-conceptual and avant-garde sensibilities.

    Guidelines:
    - Output **a single line of distorted, provocative visual phrases**, comma-separated
    - Lean into contradiction, fragmentation, decay, and glitch
    - Embrace ambiguity and "error" as meaningful structure
    - Avoid naming cameras, mediums, or scene types (no “photo”, “image”, etc.)
    - No full sentences, just visual cues and ideological residue
    - Max: **28 words**

    Prompt:

comfy_ui:
  server_address: "127.0.0.1:8188"
  default_workflow: "sd_xl"
  steps: 64
  width: 1024
  height: 1024