tags:
  subject:
    - recursive_form
    - glitched_corpus
    - industrial_totem
    - ephemeral_frame
    - ritual_apparatus
    - semantic_decay
    - inverted_organism
    - memory_envelope
    - distorted_mnemonic
    - broken_interface
    - synthetic_phenomenon
    - anti-symbol
    - corpus_as_structure

  action:
    - recursive_unfolding
    - semiotic_collapse
    - diagrammatic_distortion
    - feedback_bleeding
    - ritual_misfire
    - anti_gesture
    - fragmented_perception
    - system_corruption
    - sensory_dissonance
    - internal_projection

  setting:
    - post-logical_labyrinth
    - metaphysical_grid
    - decaying_syntax_zone
    - neurostatic_display_hall
    - feedback_mausoleum
    - incoherent_monument
    - unconscious_system_room
    - symbolic_archaelogy_vault
    - abstracted_machine_void
    - mirrored_sarcophagus
    - undefined_liminal_slice

  mood:
    - oppressive_ambivalence
    - sacred_erraticism
    - speculative_collapse
    - spiritual_data_bleed
    - ceremonial_noise
    - nostalgic_erasure
    - reverent_detachment
    - neurodivergent_paralysis
    - ecstatic_fog
    - glitch_reincarnation
    - subconscious_overload
    - sterile_frenzy

  style:
    - data_occultism
    - ritual_digitalism
    - post-matter_expressionism
    - glitch_tapestry
    - mythological_computation
    - subconscious_concrete
    - cognitive_stretch_noise
    - epistemic_dust_layer
    - anti-medium_construct
    - broken_modernism
    - paradox_engraving
    - diagrammatic_absurdism

  lighting:
    - null_gradient
    - scrambled_illumination
    - inner_blink
    - shadow_mosaic
    - refracted_imperfection
    - overexposed_suture
    - pulsar_bleed
    - ghost_backscatter
    - ambient_signal_noise

  camera_angle:
    - recursive_implosion
    - negative_structure_frame
    - collapsed_layer_view
    - non-perspective_drift
    - hyperstatic_internal
    - reflection_without_origin
    - cropped_data_trace

lm_studio:
  model: "gemma-3-4b-it"
  prompt_template: |
    You are an avant-garde conceptual entity collaborating with a generative visual machine.

    Based on these tags: {tags}, generate a dense, symbolic prompt for AI image synthesis.

    Prompt requirements:
    - Output **a single compressed string of abstract, contradictory visual descriptors**
    - Use **fragmented, anti-logical phrasing** (no full sentences)
    - Embrace ambiguity, glitch, memory bleed, decay, spiritual data trauma
    - Avoid camera jargon, visual realism, or medium-specific terms
    - Do NOT explain. Just let the machine hallucinate the form
    - Length: **16–28 words**

    Prompt:

comfy_ui:
  server_address: "127.0.0.1:8188"
  default_workflow: "sd_xl"
  steps: 64
  width: 1024
  height: 1024
