tags:
  subject:
    - unidentified_person
    - blurred_individual
    - loitering_silhouette
    - uniformed_guard
    - obscured_profile
    - suspended_motion
    - anomalous_visitor
    - hooded_figure
    - static_mannequin
    - dropped_object
    - frozen_shadow
    - corridor_watcher
    - thermal_signature
    - ghost_frame_presence
    - cloaked_intruder

  action:
    - standing_idle
    - loitering
    - passing_through
    - unauthorized_entry
    - accessing_terminal
    - elevator_waiting
    - shadow_sync
    - disconnection_event
    - collapse_event
    - disappearing_around_corner
    - failure_to_depart
    - non-interaction_loop
    - timestamp_lag_drift
    - corridor_echo_glitch

  setting:
    - underground_parking
    - metro_station
    - elevator_lobby
    - locked_server_room
    - sterile_subway_passage
    - convenience_store_backroom
    - grocery_aisle
    - restricted_hospital_floor
    - long_corridor
    - border_control_room
    - school_gymnasium
    - abandoned_reception
    - stairwell_blind_spot
    - late_night_gas_forecourt

  mood:
    - artificial_peace
    - analog_tension
    - frozen_routine
    - unnoticed_disturbance
    - bureaucratic_eeriness
    - low_level_threat
    - ambient_suspicion
    - quiet_malfunction
    - unseen_presence
    - ghost_data_overlay
    - timestamp_paranoia
    - passive_surveillance_dread

  style:
    - analog_feed
    - washed_grayscale
    - timestamp_glitch
    - security_overlay_UI
    - institutional_flatness
    - fisheye_distortion
    - interlaced_noise_frame
    - broken_pixel_grid
    - archive_loss_artifact
    - thermal_noise_overlay
    - monochrome_monitor_pass
    - motion_blur_scanlines

  lighting:
    - flickering_ceiling_light
    - red_alert_overlay
    - cold_hue_filter
    - overexposed_whiteout
    - shadowless_diffuse
    - fluorescent_banding
    - camera_flash_bloom
    - backlit_fog_haze
    - bluish_stairwell_glow
    - motion_sensor_pulse
    - ambient_security_light_fade

  camera_angle:
    - fixed_corner_lookdown
    - elevator_top_angle
    - distant_ceiling_view
    - doorway_crosswatch
    - hallway_depth_frame
    - overhead_parking_angle
    - rotating_panoramic
    - thermal_sidewatch
    - wall_mounted_static_frame
    - blink_frame_skip
    - wide_spread_monitor_array

lm_studio:
  model: "gemma-3-4b-it"
  prompt_template: |
    You are a corrupted surveillance system compiling archived footage glitches.

    Using the tags: {tags}, generate a quiet tension-filled **CCTV prompt** suitable for AI visual output.

    Guidelines:
    - Output a single **comma-separated line** of eerie institutional descriptors
    - Focus on static, analog systems, abandoned motion, timestamp unease, and unspoken events
    - You may use terms like “signal sync error”, “observer delay”, “hallway freeze frame”
    - Avoid photography or image terminology — think machine logs and passive documentation
    - Limit output to **18–28 words**

    Prompt:

comfy_ui:
  server_address: "127.0.0.1:8188"
  default_workflow: "flux_dev"
  steps: 25
  width: 1280
  height: 800
