tags:
  subject:
    - core_character
    - boss_form
    - elite_enemy
    - interactive_object
    - support_npc
    - cryptic_vendor
    - quest_icon
    - ancient_mount
    - exosuit_frame
    - mechanical_boss_core
    - relic_weapon
    - elemental_device
    - UI_focus_entity
    - biome_core
    - character_portrait_sheet
    - ambient_prop
    - level_glyph_marker
    - spawn_totem
    - warp_beacon
    - gameplay_token

  action:
    - idle_state
    - animation_loop
    - ranged_attack_frame
    - spellcasting_gesture
    - crouch_transition
    - cinematic_hover
    - stealth_ready_pose
    - ambient_movement
    - terrain_navigation
    - dialogue_interaction_idle
    - emote_triggered_action
    - save_point_activation
    - summon_effect_start
    - platform_jump_loop

  setting:
    - overworld_map_zone
    - sci_fi_command_hub
    - modular_space_dock
    - pixel_shrine_corridor
    - floating_combat_island
    - industrial_garbage_quarter
    - magical_rune_valley
    - lowpoly_cloud_arena
    - dungeon_biome_cell
    - VR_grid_map
    - dreamgate_expanse
    - co-op_ready_lobby
    - fractal_terrain_testroom
    - haunted_tower_top
    - animated_main_menu_bg

  mood:
    - immersive
    - exploratory
    - intense
    - low_pressure
    - epic
    - glitchy_retro
    - narrative_weighted
    - arcane
    - minimal_UI
    - eerie_ambient
    - action_loop_engaged
    - fast_response_zone
    - playful
    - dark_world_layer

  style:
    - concept_sketch_loose
    - UI_blueprint_wire
    - painterly_mock
    - pixel_diagram
    - lowpoly_view
    - cel_shaded_idea
    - dev_log_asset
    - stylized_fantasy_rough
    - map_concept_panel
    - isometric_rpg_style
    - combat_portrait_sheet
    - 3D_blockout_layer
    - grid_UI_marker
    - visual_novel_cutin
    - game_asset_ref_sheet

  lighting:
    - directional_edge
    - volumetric_godrays
    - shadow_bounce
    - glitched_UI_highlight
    - status_effect_aura
    - fiery_core_rim
    - ambient_spell_flicker
    - terminal_reflection
    - fog_layered
    - control_room_glow
    - overcast_surface_shine

  camera_angle:
    - isometric_grid_lock
    - orthographic_ui_frame
    - third_person_overhead
    - flyover_intro_cut
    - pixel_battle_stage_flat
    - over_the_shoulder_lore
    - UI_zoom_focus
    - character_loop_test
    - schematic_environment_slice
    - pause_menu_frame_view

lm_studio:
  model: "gemma-3-4b-it"
  prompt_template: |
    You are a game concept designer generating imagery for a prototype.

    Combine the tags: {tags} into a focused **concept art prompt** for a playable game element.

    Guidelines:
    - Output a single line of **comma-separated game art descriptors**
    - Include things like: idle frame, pixel view, battle-ready stance, level slice, UI panel, visual glyph, 3D mock
    - Avoid media references like “render”, “photo”, “screenshot”
    - Do not write in full sentences — think production notes or asset references
    - Keep it **15–25 words**, max punch, ready for ComfyUI

    Prompt:

comfy_ui:
  server_address: "127.0.0.1:8188"
  default_workflow: "sd_xl"
  steps: 64
  width: 1024
  height: 1024
