tags:
  subject:
    - core_character
    - enemy_form
    - boss_shape
    - interactive_entity
    - support_npc
    - unique_mount
    - armor_suit
    - artifact_weapon
    - energy_object
    - in-world_prop
    - signature_item
    - environmental_icon
    - architectural_marker
    - world_structure
    - concept_portrait

  action:
    - idle_state
    - combat_ready
    - spellcast_frame
    - ranged_attack
    - traversal_motion
    - cinematic_presence
    - interaction_pose
    - stealth_transition
    - exploration_moment
    - menu_idle_loop

  setting:
    - overworld_landmass
    - biomech_lab
    - ruin_city
    - pixel_cave
    - floating_island
    - battle_arena
    - lore_shrine
    - fog_forest
    - neon_highrise
    - sacred_zone
    - dream_stage
    - multiplayer_lobby
    - core_dungeon
    - fantasy_gate
    - stylized_warp_space

  mood:
    - intense
    - mystical
    - cinematic
    - dystopian
    - playful
    - dark_fantasy
    - ambient
    - adrenaline_peak
    - epic_scale
    - low_tension_loop
    - narrative_heavy

  style:
    - concept_sketch
    - high_fidelity_realism
    - UI_overlay_style
    - retro_pixel_grid
    - stylized_handpainted
    - cel_shade
    - blueprint_mock
    - game_menu_flat
    - 3d_greybox
    - painterly_fantasy
    - vector_rpg_style
    - voxel_simulation
    - dynamic_line_art
    - ink_outline_concept

  lighting:
    - moody_spot
    - directional_rim
    - lava_bloom
    - volumetric_godrays
    - reflective_floorlight
    - UI_highlight_glow
    - arcane_pulse
    - harsh_backlight
    - isometric_ambient
    - low_poly_shadowplay

  camera_angle:
    - isometric_grid_lock
    - character_design_loop
    - third_person_dynamic
    - overworld_map_focus
    - UI_lore_closeup
    - flyover_pan
    - intro_scene_cut
    - design_sheet_array
    - top_down_pathfinder

lm_studio:
  model: "gemma-3-4b-it"
  prompt_template: |
    You are a visual designer for a game prototype.

    Combine the abstract tags: {tags} into a rich, compressed concept art prompt for an AI generator.

    Guidelines:
    - Output must be **one line** of comma-separated descriptors
    - Focus on **character, setting, UI/UX, or item design**
    - Use game-dev phrasing like "idle frame", "battle-ready", "UI overlay", "character loop", "pixel mockup"
    - Avoid the words “photo”, “render”, “screenshot”
    - **Do not** write full sentences — this is not a caption
    - Keep between **15–25 words**

    Prompt:

comfy_ui:
  server_address: "127.0.0.1:8188"
  default_workflow: "sd_xl"
  steps: 64
  width: 1024
  height: 1024
