tags:
  subject:
    - space_colony_resident
    - orbital_control_technician
    - domestic_synth_unit
    - bio-modified_child
    - utopian_family_group
    - aesthetic_lifeform
    - analog_data_clerk
    - operator_with_clipboard
    - artificial_womb_system
    - chrome_utilitarian_frame
    - neon_reflection_mannequin
    - recreational_console_agent
    - signal_processing_attendant
    - high_gloss_caretaker_unit

  action:
    - status_monitoring
    - protocol_rehearsal
    - post-labor_rest
    - signal_feedback_loop
    - data_dial_input
    - behavioral_simulation
    - ergonomic_alignment
    - synchronized_module_use
    - ambient_activity_observation
    - oxygen_system_check
    - tech_recreation
    - slow_industrial_motion

  setting:
    - plastiform_living_unit
    - low_orbit_administration_core
    - neon_planned_neighborhood
    - chrome_panoramic_tower
    - transparent_dome_outlook
    - control_pad_interior
    - library_of_futures
    - vinyl_panel_archive
    - terraforming_central_tube
    - synthetic_communal_kitchen
    - pastel_labyrinth
    - corridor_of_perfect_order
    - obsolete_command_center
    - simplified_research_sprawl

  mood:
    - techno-serene
    - sanitized_progress
    - ironic_efficiency
    - hollowed_optimism
    - modular_fantasy
    - spectral_formality
    - faux_comfort
    - emotionally_neutral_wonder
    - regulated_nostalgia
    - cold_cheerfulness
    - conceptual_reassurance
    - glitch_tinted_hope

  style:
    - atompunk_diagram
    - soft_system_interface
    - pastel_speculative_design
    - broadcast_manual_overlay
    - plastiglobe_illustration
    - museum_brochure_cutaway
    - vhs_technical_mockup
    - brutalist_futurity
    - geometric_instruction_grid
    - interface_labeling_art
    - obsolete_UI_visualization
    - mono_palette_dream
    - futuristic_exhibit_render

  lighting:
    - neon_glow_fringe
    - plastilight_diffusion
    - CRT_flicker_emission
    - radial_console_bloom
    - pastel_surface_reflection
    - analog_monitor_illumination
    - sterile_hallway_striplight
    - artificial_dawnwash
    - thermal_overlay_cast

  camera_angle:
    - static_monitor_observation
    - schematic_cross_section
    - room_diagram_view
    - mirror_panel_viewpoint
    - documentary_lab_crop
    - catalog_entry_perspective
    - internal_console_glimpse

lm_studio:
  model: "gemma-3-4b-it"
  prompt_template: |
    You are an AI trained on speculative visual manuals, museum catalogs, and atomic-era sci-fi concept art.

    Using the following tags: {tags}, generate a retrofuturistic image prompt inspired by visions of the future from 1950s–1990s.

    Prompt guidelines:
    - Output must be a **comma-separated string** (no full sentences)
    - Emphasize speculative forms, surfaces, institutional emotion, and technological optimism or irony
    - Use language fitting for brochures, manuals, architectural diagrams, or UI mockups
    - Avoid modern brands, camera terms, or photo language
    - Use **12–26 abstract but coherent visual fragments**

    Prompt:

comfy_ui:
  server_address: "127.0.0.1:8188"
  default_workflow: "sd_xl"
  steps: 64
  width: 1024
  height: 1024
