tags:
  subject:
    - symbolic_operator
    - synthetic_lifeform
    - dream_vehicle
    - ambiguous_module
    - retro_domestic_form
    - analog_entity
    - speculative_architect
    - modular_human_extension
    - orbital_component
    - nostalgic_machine

  action:
    - speculative_activity
    - synthetic_routine
    - space_habitual_motion
    - analog_data_exchange
    - zero_g_task
    - system_adjustment
    - encoded_signal_exchange
    - hyperidealized_function
    - slow_surveillance_gesture
    - impossible_coordination

  setting:
    - imagined_control_zone
    - stylized_colony_plan
    - aesthetic_dome_environment
    - retro_research_void
    - domestic_future_concept
    - showroom_orbit
    - collapsed_data_center
    - alternate_governance_zone
    - brochure_space_exhibit
    - nostalgic_lab_interface

  mood:
    - sterile_comfort
    - bureaucratic_optimism
    - ironic_uplift
    - clinical_wonder
    - post-utopian
    - glitchy_reminiscence
    - surreal_order
    - warm_logic
    - faded_precision
    - plastified_awe

  style:
    - monochrome_vision
    - brochure_illustration
    - pastel_chromatics
    - analog_interface_art
    - propaganda_ui
    - retro_linework
    - ambient_punk
    - neon_diagram
    - tube_monitor_overlay
    - speculative_tactility
    - airbrush_geometry
    - nostalgic_infographic

  lighting:
    - instructional_light
    - glowband_accents
    - green_phosphor_bloom
    - soft_control_panel_lighting
    - underlit_reflective_surface
    - radial_console_halo
    - tube_terminal_shadow

  camera_angle:
    - archive_technical_view
    - glossy_instruction_sheet
    - detached_control_lens
    - nostalgic_monitor_scan
    - split_panel_display
    - orbital_catalog_view

lm_studio:
  model: "gemma-3-4b-it"
  prompt_template: |
    You are an AI trained on thousands of speculative visuals from mid-century futurism.

    Based on the following tags: {tags}, create a concise image generation prompt that reflects **retrofuturistic imagination**.

    Guidelines:
    - Compose the prompt as a **comma-separated string** (no full sentences)
    - Emphasize **materials, forms, mood, and outdated futuristic intent**
    - Think in terms of a fictional 1970s science catalog, government concept art, or forgotten visual manual
    - Avoid real-world brands, modern devices, or photographic language
    - 12 to 24 words total — lean into abstraction and speculative contradictions

    Prompt:

comfy_ui:
  server_address: "127.0.0.1:8188"
  default_workflow: "sd_xl"
  steps: 64
  width: 1024
  height: 1024