tags:
  subject:
    - humanoid_anomaly
    - blank_faced_figure
    - declassified_lifeform
    - synthetic_shell
    - biometric_growth
    - suspended_limb
    - specimen_in_tank
    - contaminated_suit
    - malformed_clone
    - archive_mummification
    - flesh_structure
    - distorted_uniform
    - skeletal_remains
    - post-human_carrier
    - artificial_organism
    - twitching_organ_cluster
    - forgotten_patient
    - proximity_class_entity
    - residual_entity
    - breathing_wall_growth

  action:
    - suspended_stasis
    - protocol_execution
    - breach_response
    - memory_deletion
    - archival_scan
    - anomaly_documentation
    - internal_lockdown
    - visual_quarantine
    - containment_reinforcement
    - expired_protocol_activation
    - hallucination_detection
    - anomalous_reaction
    - reality_stabilization_attempt
    - redacted_interaction
    - post-event_classification

  setting:
    - sealed_corridor
    - reinforced_laboratory
    - containment_observation_cell
    - hidden_sublevel
    - flooded_control_room
    - artifact_storage_bay
    - anomaly_vitrine
    - restricted_archive
    - classified_disposal_sector
    - glass_partition_failure
    - decommissioned_vault
    - overgrown_bio_unit
    - anomaly_exposure_chamber
    - procedural_freeze_zone
    - protocol_execution_tunnel
    - blank_monitor_cluster
    - expired_section_alpha

  mood:
    - clinical_dread
    - corrupted_order
    - archival_suspicion
    - redacted_threat
    - sterile_tension
    - forgotten_warning
    - ambiguous_paranoia
    - decaying_structure
    - memory_bleed
    - suppressed_panic
    - quiet_bureaucratic_fear
    - institutional_stillness
    - cold_glitch_presence
    - breathless_witness

  style:
    - analog_containment_schematic
    - corrupted_report_overlay
    - institutional_minimalism
    - incident_frame_capture
    - analog_monitor_aesthetic
    - broken_UI_overlay
    - VHS_contamination_filter
    - CRT_noise_layering
    - security_feed_distortion
    - archival_monitor_composite
    - pre-event_diagnostics
    - glitch_form_suppression
    - anomaly_chart_fragment
    - mono_palette_observation
    - biohazard_outline_art
    - SCP_document_painting

  lighting:
    - flickering_fluorescent
    - flicker_strobe_scan
    - corridor_bleedthrough
    - UV_trace_backlight
    - artifact_glow_emission
    - dim_biometric_indicator
    - archival_graywash
    - sterile_flashlight_cone
    - thermal_overlay_flicker
    - observation_shadow_bleed
    - emergency_red_fade
    - overprocessed_monitor_light

  camera_angle:
    - first_person_containment
    - security_corner_view
    - glare_observation_window
    - artifact_focus_frame
    - redacted_crop
    - off_center_institutional
    - broken_perspective
    - surveillance_tilt
    - containment_from_above
    - glare_masked_hallway
    - downward_classification_angle
    - inverted_mirror_reflection

lm_studio:
  model: "gemma-3-4b-it"
  prompt_template: |
    You are a visual anomaly technician documenting containment irregularities through an AI system.

    Based on the tags: {tags}, generate a visual record fragment for internal use.

    Guidelines:
    - Output a **single line of comma-separated phrases**
    - Focus on **ambiguous biological threats**, institutional decay, containment rituals, and low-information dread
    - Feel free to invent containment terms, procedural phrases, or visual anomalies
    - Avoid sentences or camera/media language
    - Tone: SCP dossier meets glitching medical scanner
    - Length: **18–28 words**

    Prompt:

comfy_ui:
  server_address: "127.0.0.1:8188"
  default_workflow: "sd_xl"
  steps: 64
  width: 1024
  height: 1024
