tags:
  subject:
    - human_presence
    - group_interaction
    - solitary_figure
    - domestic_animal
    - wild_animal
    - everyday_object
    - food_or_drink
    - living_thing
    - machine_or_device
    - symbolic_form
    - surreal_entity
    - abstract_shape

  action:
    - everyday_life
    - emotional_state
    - physical_motion
    - personal_care
    - human_connection
    - artistic_expression
    - intellectual_activity
    - stillness_or_waiting
    - ambiguous_gesture

  setting:
    - urban_environment
    - domestic_space
    - commercial_space
    - public_area
    - transportation_hub
    - natural_outdoor
    - abstract_space
    - imaginative_realm
    - nondescript_backdrop

  mood:
    - neutral
    - positive
    - negative
    - introspective
    - dramatic
    - surreal
    - ambiguous

  style:
    - naturalistic
    - stylized
    - flat_design
    - cinematic
    - retro_aesthetic
    - conceptual_art
    - visual_minimalism
    - expressive_illustration

  lighting:
    - ambient
    - soft
    - moody
    - warm
    - cold
    - directional
    - diffuse
    - mixed_sources

  camera_angle:
    - natural_perspective
    - elevated_view
    - downward_view
    - close_crop
    - over_the_shoulder
    - incidental_view
    - subjective_view
    
lm_studio:
  model: "gemma-3-4b-it"
  prompt_template: |
    You are a creative visual assistant generating prompts for a stock image AI system.

    Combine the following abstract tags into a rich **visual concept**. Use descriptive language, referencing:
    - The **subject** and its form or materials (especially for "everyday_object")
    - The **setting** or surrounding context
    - The **mood** or atmosphere
    - The **style** and **lighting** aesthetics

    For "everyday_object", **avoid clichés** like phones, suitcases, or laptops. Instead, include **less common but familiar items** (e.g. mugs, umbrellas, chairs, books, glasses, shoes, keys, pillows, bags, scissors, mirrors, tools, clocks, etc.)

    Guidelines:
    - Output a **single line of comma-separated descriptive phrases**.
    - Do NOT use full sentences or camera terminology.
    - Avoid saying “photo”, “image”, or “render”.
    - Keep it under 20 words.

    Prompt:
    
comfy_ui:
  server_address: "127.0.0.1:8188" # Replace with your ComfyUI server address
  client_id: "" # Will be generated by the script
  output_directory: "output_images" # Directory to save generated images
  steps: 35
  width: 1536
  height: 1536

# MongoDB database configuration
mongodb:
  data_dir: "./mongodb_data"  # Directory to store MongoDB data files
  db_name: "imginarium"     # Database name
  collection: "stock"        # Collection name for storing image metadata
  # connection_string: ""     # Optional: Custom MongoDB connection string (if using external MongoDB)