tags:
  subject:
    - individual_person
    - small_group
    - family_dynamic
    - domestic_pet
    - urban_wildlife
    - household_item
    - workspace_object
    - plant_life
    - digital_device
    - tool_or_accessory
    - neutral_symbol
    - decorative_shape
    - cozy_element

  action:
    - daily_activity
    - emotional_expression
    - focused_task
    - social_interaction
    - leisure_moment
    - creative_process
    - care_or_gesture
    - thoughtful_pause
    - passive_motion

  setting:
    - modern_home_interior
    - office_space
    - living_room
    - public_park
    - transit_area
    - cafe_or_bistro
    - kitchen_counter
    - city_street_corner
    - bright_studio_backdrop
    - neutral_background

  mood:
    - calm
    - cheerful
    - thoughtful
    - motivated
    - peaceful
    - collaborative
    - practical
    - content
    - gentle
    - sincere

  style:
    - clean_realism
    - editorial_minimalism
    - lifestyle_soft_focus
    - pastel_flat
    - muted_conceptual
    - modern_visual_language
    - business_casual
    - health_wellness_styling
    - abstract_corporate

  lighting:
    - natural_daylight
    - softbox_even
    - indirect_sunlight
    - warm_indoor
    - subtle_shadowplay
    - neutral_fill_light
    - backlit_diffusion
    - window_light_bounce

  camera_angle:
    - level_eye_view
    - three_quarter_frame
    - above_tabletop
    - close_crop
    - over_shoulder
    - perspective_peek
    - lifestyle_wide
    - subject_centered

lm_studio:
  model: "gemma-3-4b-it"
  prompt_template: |
    You are creating a prompt for a **stock image generator**.

    Use the following tags: {tags}

    Guidelines:
    - Output should be a single line of **comma-separated phrases**
    - Focus on **human presence, lifestyle elements, clean visuals, and contextual clarity**
    - Especially for everyday objects, be **specific** and avoid clichés (no phones, laptops, suitcases)
    - Use clear visual language: form, material, mood, light, setting
    - Do **not** use full sentences or mention cameras, photos, or image types
    - Keep it under **20 words**

    Prompt:

comfy_ui:
  server_address: "127.0.0.1:8188"
  default_workflow: "flux_dev"
  steps: 35
  width: 1536
  height: 1536
