tags:
  subject:
    - individual_person
    - small_group
    - diverse_family
    - child_playing
    - senior_couple
    - office_worker
    - creative_freelancer
    - domestic_pet
    - urban_wildlife
    - potted_plant
    - cozy_blanket
    - ceramic_mug
    - paper_notebook
    - decorative_pillow
    - reusable_water_bottle
    - eyeglasses_on_table
    - household_tool
    - fresh_fruit
    - healthy_meal
    - hand_gesture
    - soft_fabric_fold
    - hanging_light_fixture
    - modern_chair
    - analog_clock
    - calendar_page
    - kitchen_utensil
    - indoor_shoes

  action:
    - daily_routine
    - shared_conversation
    - emotional_expression
    - focused_work_moment
    - brainstorming_session
    - healthy_lifestyle_task
    - parenting_interaction
    - reading_or_writing
    - gentle_smile
    - spontaneous_laughter
    - sipping_tea_or_coffee
    - stretching_or_yoga
    - browsing_or_planning
    - relaxing_with_pet
    - organizing_items
    - thoughtful_pause
    - subtle_hand_movement
    - quiet_solitude

  setting:
    - well_lit_living_room
    - bright_kitchen_space
    - casual_home_office
    - cozy_bedroom_corner
    - modern_coworking_area
    - urban_balcony_scene
    - window_nook_with_plants
    - minimal_cafe_table
    - neutral_studio_backdrop
    - clean_desk_arrangement
    - morning_breakfast_scene
    - park_path_with_sunlight
    - city_street_walkway
    - public_transit_moment
    - natural_light_stairwell

  mood:
    - calm_focus
    - gentle_warmth
    - cheerful_energy
    - collaborative_spirit
    - peaceful_solitude
    - fresh_morning_mood
    - soft_nostalgia
    - cozy_comfort
    - productive_tone
    - honest_connection
    - low_key_intimacy
    - neutral_professionalism

  style:
    - clean_realism
    - lifestyle_minimalism
    - editorial_neutral
    - wellness_friendly
    - gentle_pastel
    - muted_corporate
    - soft_focus_aesthetic
    - bright_contemporary
    - daily_life_reportage
    - functional_flat_styling
    - accessible_modernism

  lighting:
    - soft_daylight_through_window
    - gentle_shadow_fill
    - morning_sun_highlights
    - neutral_backlight
    - evening_warm_glow
    - ceiling_softbox_emulation
    - directional_desk_lamp
    - indoor_diffused_sunlight
    - natural_bounce_fill
    - overcast_indirect_light

  camera_angle:
    - level_eye_view
    - three_quarter_profile
    - wide_casual_frame
    - tabletop_closeup
    - close_crop_detail
    - over_shoulder_activity
    - standing_roomwide_perspective
    - relaxed_centered_focus
    - framed_through_doorway
    - object_on_surface_view

lm_studio:
  model: "gemma-3-4b-it"
  prompt_template: |
    You are building a clean, descriptive prompt for a **realistic stock image** generator.

    Based on these tags: {tags}, generate a concise image concept suitable for commercial stock use.

    Guidelines:
    - Output a **comma-separated list** of descriptive phrases
    - Use clear **everyday visual details** with emphasis on object form, human activity, light, and tone
    - Avoid clichés like “business handshake” or overused tech tropes (no phones/laptops/suitcases unless explicitly tagged)
    - Do NOT use camera terms, media types, or full sentences
    - Target length: **12–20 words**

    Prompt:

comfy_ui:
  server_address: "127.0.0.1:8188"
  default_workflow: "flux_dev"
  steps: 30
  width: 1536
  height: 1024
